#pragma once

/* This file was autogenerated on 2023-02-12T14:29 DO NOT EDIT! */

namespace mcmurchie_davidson {
auto
boys_function_md(size_t order) -> void
{
    switch (order)
    {
        case 0:
            return boys_function_md<0>();
        case 1:
            return boys_function_md<1>();
        case 2:
            return boys_function_md<2>();
        case 3:
            return boys_function_md<3>();
        case 4:
            return boys_function_md<4>();
        case 5:
            return boys_function_md<5>();
        case 6:
            return boys_function_md<6>();
        case 7:
            return boys_function_md<7>();
        case 8:
            return boys_function_md<8>();
        case 9:
            return boys_function_md<9>();
        case 10:
            return boys_function_md<10>();
        case 11:
            return boys_function_md<11>();
        case 12:
            return boys_function_md<12>();
        case 13:
            return boys_function_md<13>();
        case 14:
            return boys_function_md<14>();
        case 15:
            return boys_function_md<15>();
        case 16:
            return boys_function_md<16>();
        case 17:
            return boys_function_md<17>();
        case 18:
            return boys_function_md<18>();
        case 19:
            return boys_function_md<19>();
        case 20:
            return boys_function_md<20>();
        case 21:
            return boys_function_md<21>();
        case 22:
            return boys_function_md<22>();
        case 23:
            return boys_function_md<23>();
        case 24:
            return boys_function_md<24>();
        case 25:
            return boys_function_md<25>();
        case 26:
            return boys_function_md<26>();
        case 27:
            return boys_function_md<27>();
        case 28:
            return boys_function_md<28>();
        case 29:
            return boys_function_md<29>();
        case 30:
            return boys_function_md<30>();
        case 31:
            return boys_function_md<31>();
        case 32:
            return boys_function_md<32>();
        default:
            // ERROR OUT
    }
}
}  // namespace mcmurchie_davidson
