#pragma once

#include <array>

/* This file was autogenerated on 2023-02-12T14:29 DO NOT EDIT! */

namespace mcmurchie_davidson {
/**
 * Pretabulated values of given order.
 *
 * @tparam order Order of the table to fetch.
 * @return table of values.
 */
template <auto order>
inline constexpr std::array<std::array<double, 7>, 121> pretabulated();
}  // namespace mcmurchie_davidson

#include "tables/BFunc_01.hpp"
#include "tables/BFunc_02.hpp"
#include "tables/BFunc_03.hpp"
#include "tables/BFunc_04.hpp"
#include "tables/BFunc_05.hpp"
#include "tables/BFunc_06.hpp"
#include "tables/BFunc_07.hpp"
#include "tables/BFunc_08.hpp"
#include "tables/BFunc_09.hpp"
#include "tables/BFunc_10.hpp"
#include "tables/BFunc_11.hpp"
#include "tables/BFunc_12.hpp"
#include "tables/BFunc_13.hpp"
#include "tables/BFunc_14.hpp"
#include "tables/BFunc_15.hpp"
#include "tables/BFunc_16.hpp"
#include "tables/BFunc_17.hpp"
#include "tables/BFunc_18.hpp"
#include "tables/BFunc_19.hpp"
#include "tables/BFunc_20.hpp"
#include "tables/BFunc_21.hpp"
#include "tables/BFunc_22.hpp"
#include "tables/BFunc_23.hpp"
#include "tables/BFunc_24.hpp"
#include "tables/BFunc_25.hpp"
#include "tables/BFunc_26.hpp"
#include "tables/BFunc_27.hpp"
#include "tables/BFunc_28.hpp"
#include "tables/BFunc_29.hpp"
#include "tables/BFunc_30.hpp"
#include "tables/BFunc_31.hpp"
#include "tables/BFunc_32.hpp"
