/* This file was autogenerated on 2023-04-10T15:12 DO NOT EDIT! */

#pragma once

#include <array>

namespace pade {
/**@{ Pretabulated coefficients for the [M/N] Padé approximants of the Boys function of orders 1 <= O <= 32.
 *  The coefficients are in natural order: from lowest to highest power.
 */
/** Numerator of Padé approximant */
template <auto M, auto N, auto order>
inline constexpr auto Ps() -> std::array<double, M + 1>;
/** Denominator of Padé approximant */
template <auto M, auto N, auto order>
inline constexpr auto Qs() -> std::array<double, N + 1>;
}  // namespace pade
/**@}*/

#include "approximants/Coefficients_05_06.hpp"
#include "approximants/Coefficients_09_10.hpp"
#include "approximants/Coefficients_15_16.hpp"
#include "approximants/Coefficients_25_26.hpp"
