/* This file was autogenerated on 2023-02-17T18:32 DO NOT EDIT! */

#include <stdexcept>
#include <string>

namespace pade_25_26 {
auto
boys_function(size_t order, const std::vector<double>& xs) -> void
{
    switch (order)
    {
        case 0:
            return cpu::boys_function<0>(xs.data());
        case 1:
            return cpu::boys_function<1>(xs.data());
        case 2:
            return cpu::boys_function<2>(xs.data());
        case 3:
            return cpu::boys_function<3>(xs.data());
        case 4:
            return cpu::boys_function<4>(xs.data());
        case 5:
            return cpu::boys_function<5>(xs.data());
        case 6:
            return cpu::boys_function<6>(xs.data());
        case 7:
            return cpu::boys_function<7>(xs.data());
        case 8:
            return cpu::boys_function<8>(xs.data());
        case 9:
            return cpu::boys_function<9>(xs.data());
        case 10:
            return cpu::boys_function<10>(xs.data());
        case 11:
            return cpu::boys_function<11>(xs.data());
        case 12:
            return cpu::boys_function<12>(xs.data());
        case 13:
            return cpu::boys_function<13>(xs.data());
        case 14:
            return cpu::boys_function<14>(xs.data());
        case 15:
            return cpu::boys_function<15>(xs.data());
        case 16:
            return cpu::boys_function<16>(xs.data());
        case 17:
            return cpu::boys_function<17>(xs.data());
        case 18:
            return cpu::boys_function<18>(xs.data());
        case 19:
            return cpu::boys_function<19>(xs.data());
        case 20:
            return cpu::boys_function<20>(xs.data());
        case 21:
            return cpu::boys_function<21>(xs.data());
        case 22:
            return cpu::boys_function<22>(xs.data());
        case 23:
            return cpu::boys_function<23>(xs.data());
        case 24:
            return cpu::boys_function<24>(xs.data());
        case 25:
            return cpu::boys_function<25>(xs.data());
        case 26:
            return cpu::boys_function<26>(xs.data());
        case 27:
            return cpu::boys_function<27>(xs.data());
        case 28:
            return cpu::boys_function<28>(xs.data());
        case 29:
            return cpu::boys_function<29>(xs.data());
        case 30:
            return cpu::boys_function<30>(xs.data());
        case 31:
            return cpu::boys_function<31>(xs.data());
        case 32:
            return cpu::boys_function<32>(xs.data());
        default:
            throw invalid_argument("Maximum supported order is 32. Requested order is " + std::to_string(order));
    }
}
}  // namespace pade_25_26
