#pragma once

/* This file was autogenerated on 2023-02-12T14:30 DO NOT EDIT! */

namespace pade_25_26 {
auto
boys_function_pade(size_t order) -> void
{
    switch (order)
    {
        case 0:
            return boys_function_pade<0>();
        case 1:
            return boys_function_pade<1>();
        case 2:
            return boys_function_pade<2>();
        case 3:
            return boys_function_pade<3>();
        case 4:
            return boys_function_pade<4>();
        case 5:
            return boys_function_pade<5>();
        case 6:
            return boys_function_pade<6>();
        case 7:
            return boys_function_pade<7>();
        case 8:
            return boys_function_pade<8>();
        case 9:
            return boys_function_pade<9>();
        case 10:
            return boys_function_pade<10>();
        case 11:
            return boys_function_pade<11>();
        case 12:
            return boys_function_pade<12>();
        case 13:
            return boys_function_pade<13>();
        case 14:
            return boys_function_pade<14>();
        case 15:
            return boys_function_pade<15>();
        case 16:
            return boys_function_pade<16>();
        case 17:
            return boys_function_pade<17>();
        case 18:
            return boys_function_pade<18>();
        case 19:
            return boys_function_pade<19>();
        case 20:
            return boys_function_pade<20>();
        case 21:
            return boys_function_pade<21>();
        case 22:
            return boys_function_pade<22>();
        case 23:
            return boys_function_pade<23>();
        case 24:
            return boys_function_pade<24>();
        case 25:
            return boys_function_pade<25>();
        case 26:
            return boys_function_pade<26>();
        case 27:
            return boys_function_pade<27>();
        case 28:
            return boys_function_pade<28>();
        case 29:
            return boys_function_pade<29>();
        case 30:
            return boys_function_pade<30>();
        case 31:
            return boys_function_pade<31>();
        case 32:
            return boys_function_pade<32>();
        default:
            // ERROR OUT
    }
}
}  // namespace pade_25_26
